### ISSUE TITLE
TasitAction.Contract transaction reversion handling

### ISSUE THREAD

**Issue by marcelomorgado** [tasitlabs/TasitSDK#155]
We have no expected behavior when `eth_send`/`eth_call` reversion occurs.
Note: I've faced this problem when I was writing `safeTransferFrom` test case and expected an exception when transferring token to a contract that not implement  `onERC721Received`.

Below an example of how `ethers` handles with that situation [refs](https://github.com/ethers-io/ethers.js/issues/368#issuecomment-445041029):

```javascript
contract.someMethod(1, 2, 3).then(
  (result) => {
    // success
  }, 
  (error) => {
    console.log(error);
    // error.reason - The Revert reason; this is what you probably care about. :)
    // Additionally:
    // - error.address - the contract address
    // - error.args - [ BigNumber(1), BigNumber(2), BigNumber(3) ] in this case
    // - error.method - "someMethod()" in this case
    // - error.errorSignature - "Error(string)" (the EIP 838 sighash; supports future custom errors)
    // - error.errorArgs - The arguments passed into the error (more relevant post EIP 838 custom errors)
    // - error.transaction - The call transaction used
});
```

Our code for reference:

```javascript
// draft
txSubscription = contract.toBeRejected();
```

- I think that we can't throw an exception since our contract write-function is sync.
- Make sense that user should register an error listener when instantiating a contract?

Another idea?

**Comment by pcowgill** [comment]
Glad you brought this up. Yeah, this is what I was picturing when I mentioned error events from the contract rather than from other listeners. 

I think for each actionSubscription the user should ideally be able to set up an error listener for that action before sending the action or immediatelt afterwards but before it if processed and rejected by the blockchain.

And yes, being able to configure a catch-all error listener that applies for all actions for that contract by default seems worth adding too.

**Comment by marcelomorgado** [comment]
A) So, both should work?
```javascript
// draft
const s = contract.subscribe();
s.on("error", callback); // catch revert error
txSubscription = contract.toBeRejected();
```
and
```javascript
// draft
txSubscription = contract.toBeRejected();
txSubscription.on("error", callback); // catch revert error
```

Notes: 
- For now `ContractSubscription` trigger error event that occurs inside of ther class;
- Make sense have 0:1  `ContractSubscription` instances per `Contract` (I think that will help to implement this easier).

B) Is that what you are thinking about?

```javascript
// draft
const s = contract.subscribe(onErrorCallback); // as optional function
```

**Comment by pcowgill** [comment]
> So, both should work?

Yes, I think so.

> ```
> // draft
> const s = contract.subscribe();
> s.on("error", callback); // catch revert error
> txSubscription = contract.toBeRejected();
> ```

In this ^ version, I'm wondering whether just doing the `.on` directly on the contract work instead of storing `s` and doing it there.

> Notes:
>     For now ContractSubscription trigger error event that occurs inside of ther class;

I think this relates to my suggestion for the ActionSubscription above. If we changed the ActionSubscription, it would work the same as this one, right?

>     Make sense have 0:1 ContractSubscription instances per Contract (I think that will help to implement this easier).

Yeah, 0 or 1 `ContractSubscription`'s (a.k.a. `ContractEventsSubscription`'s) per contract sounds good.

> B) Is that what you are thinking about?

No, I was picturing putting the error listener on the contract after subscribing.

**Comment by marcelomorgado** [comment]
A) :+1: 

B) I'm with doubt about these two sentences:

```javascript
// doing the .on directly on the contract
contract.on("error", onErrorListener);

// putting the error listener on the contract after subscribing.
contract.subscribe().on("error", onErrorListener);
```
Which one is the correct?

C) Yes. I agree with you. Double-checking: All errors occurring on `ContractEventsSubscription` and `TransactionSubscription` should emit a event to `Contract` error listener. Right?

D) :+1: 

E) Same as B.
 
If I haven't undestand you yet, maybe write some code draft can help me.

**Comment by marcelomorgado** [comment]
Could we close this one?

**Comment by pcowgill** [comment]
Yep!
